CREATE DATABASE IF NOT EXISTS eb;
CREATE DATABASE IF NOT EXISTS teams;
CREATE DATABASE IF NOT EXISTS aa;
CREATE DATABASE IF NOT EXISTS pdp;
CREATE DATABASE IF NOT EXISTS spdashboard;
CREATE DATABASE IF NOT EXISTS invite;
CREATE DATABASE IF NOT EXISTS userlifecycle;
CREATE DATABASE IF NOT EXISTS spdashboard;
CREATE DATABASE IF NOT EXISTS sbs;

CREATE USER IF NOT EXISTS 'ebrw'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON eb.* TO 'ebrw'@'%';

CREATE USER IF NOT EXISTS 'teamsrw'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON teams.* TO 'teamsrw'@'%';

CREATE USER IF NOT EXISTS 'aarw'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON aa.* TO 'aarw'@'%';

CREATE USER IF NOT EXISTS 'pdprw'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON pdp.* TO 'pdprw'@'%';

CREATE USER IF NOT EXISTS 'spdrw'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON spdashboard.* TO 'spdrw'@'%';

CREATE USER IF NOT EXISTS 'inviterw'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON invite.* TO 'inviterw'@'%';

CREATE USER IF NOT EXISTS 'userlifecyclerw'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON userlifecycle.* TO 'userlifecyclerw'@'%';

CREATE USER IF NOT EXISTS 'spdrwrw'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON spdashboard.* TO 'spdrwrw'@'%';

CREATE USER IF NOT EXISTS 'sbs'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON sbs.* TO 'sbs'@'%';
